export * from './user.model';
export * from './announcement.model';
export * from './academic.model';
export * from './resource.model';
export * from '../scrapers/models/scraperSource.model';
export * from '../scrapers/models/scraperRun.model';
export * from '../scrapers/models/scraperItem.model';
export * from '../scrapers/models/scraperChange.model';
export * from '../scrapers/models/scraperLock.model';
